version: "3.7"
services:

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672"
      - "15672:15672"

  sender:
    image: openjdk:8-jre-slim
    entrypoint: ["java", "-jar", "/tmp/app.jar"]
    environment:
      SPRING_RABBITMQ_HOST: rabbit
    ports:
      - "8082:8080"
    volumes:
      - "../sender/build/libs/sender-0.0.1-SNAPSHOT.jar:/tmp/app.jar"
